version: '2'
services:
  web:
    restart: always
    build: ./web
    expose:
     - "8000"
    ports:
      - "8000:8000"
    volumes:
     - .:/code
    working_dir: /code/web
    command: /usr/local/bin/gunicorn -w 1 -b :8000 ner_flask:app